version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    command: ["sh", "-c", "while ! nc -z mysql 3306; do sleep 1; done; go run main.go"]
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
